import {
    Package, ShoppingCart, Factory, Wrench, Users, Truck, Banknote, Car,
    BarChart3, Settings, PackageSearch, FolderTree, Tags, Layers,
    SlidersHorizontal, ArrowLeftRight, MapPin, ClipboardCheck, RefreshCw,
    ScanBarcode, FileText, ClipboardList, Receipt, Undo2, ListOrdered,
    Percent, CalendarClock, PauseCircle, FileInput, ListPlus, PackageCheck,
    FileSpreadsheet, FileMinus, PackageX, Ship, Scale, KanbanSquare,
    HardHat, Timer, CarFront, ShieldCheck, Gauge, FileStack, Award,
    MessageSquare, UsersRound, BadgeCheck, TrendingUp, BookOpen, PenLine,
    ListTree, HandCoins, Hourglass, Rows3, Landmark, GitCompare, Calendar,
    Lock, Columns2, Search, Shuffle, Cog, GitBranch, AlertTriangle, Upload,
    LayoutDashboard, Clock, Building2, UserCog, KeyRound, ScrollText,
    DatabaseBackup, Coins, Hash, Printer, Mail, Bell, HeartPulse,
} from 'lucide-react';

export const MODULES = [
    {
        key: 'inventory',
        title: 'Inventory Management',
        description: 'Parts catalogue, stock control, bin locations, stock takes and reorder management.',
        icon: Package,
        color: 'bg-orange-600',
        status: 'Planned',
        subModules: [
            { title: 'Parts Catalogue', description: 'Master data for every part — SKUs, OEM numbers, barcodes, images.', icon: PackageSearch },
            { title: 'Stock Control', description: 'Real-time stock levels per branch, adjustments and movement ledger.', icon: Layers },
            { title: 'Bin Locations', description: 'Physical warehouse shelf and bin mapping.', icon: MapPin },
            { title: 'Stock Takes', description: 'Full counts, cycle counts and variance resolution.', icon: ClipboardCheck },
            { title: 'Reorder Management', description: 'Min/max levels, reorder points and auto purchase requests.', icon: RefreshCw },
            { title: 'Parts Fitment Guide', description: 'Which parts fit which vehicles — make, model, year, engine.', icon: Car },
            { title: 'Serial & Batch Tracking', description: 'Individual tracking for engines, gearboxes and batches.', icon: ScanBarcode },
            { title: 'Category Management', description: 'Hierarchical parts categorisation tree.', icon: FolderTree },
        ],
    },
    {
        key: 'sales',
        title: 'Sales & POS',
        description: 'Counter sales, quotations, invoicing, price lists and promotions.',
        icon: ShoppingCart,
        color: 'bg-blue-600',
        status: 'Planned',
        subModules: [
            { title: 'Counter Sales (POS)', description: 'Fast walk-in sales with barcode scanning and split payments.', icon: ShoppingCart },
            { title: 'Quotations', description: 'Formal quotes with expiry and one-click conversion.', icon: FileText },
            { title: 'Sales Orders', description: 'Back-orders, stock reservations and delivery scheduling.', icon: ClipboardList },
            { title: 'Tax Invoices', description: 'Gapless invoicing with VAT and GL posting.', icon: Receipt },
            { title: 'Credit Notes & Returns', description: 'Customer returns, refunds and exchanges.', icon: Undo2 },
            { title: 'Price Lists', description: 'Retail, trade, wholesale and VIP pricing tiers.', icon: ListOrdered },
            { title: 'Promotions & Discounts', description: 'Time-based deals, bulk discounts and bundles.', icon: Percent },
            { title: 'Lay-by Management', description: 'Deposit-based payment plans.', icon: CalendarClock },
            { title: 'Delivery Notes', description: 'Delivery documentation for shipped orders.', icon: Truck },
        ],
    },
    {
        key: 'purchasing',
        title: 'Purchasing',
        description: 'Purchase orders, goods receiving, supplier invoices and imports.',
        icon: Factory,
        color: 'bg-teal-600',
        status: 'Planned',
        subModules: [
            { title: 'Purchase Requisitions', description: 'Internal requests to buy parts, auto-raised from reorder alerts.', icon: ListPlus },
            { title: 'Purchase Orders', description: 'Formal orders to suppliers with approvals and currency support.', icon: FileInput },
            { title: 'Goods Received Notes', description: 'Receiving, quality checks, putaway and landed costs.', icon: PackageCheck },
            { title: 'Supplier Invoices', description: '3-way matching against PO and GRN.', icon: FileSpreadsheet },
            { title: 'Supplier Credit Notes', description: 'Credits for returns, corrections and rebates.', icon: FileMinus },
            { title: 'Returns to Supplier', description: 'RMA-tracked returns of damaged or incorrect goods.', icon: PackageX },
            { title: 'Import Management', description: 'International shipments, customs and clearing.', icon: Ship },
            { title: 'Price Comparison', description: 'Compare supplier costs for the same part.', icon: Scale },
        ],
    },
    {
        key: 'workshop',
        title: 'Workshop',
        description: 'Job cards, labour, technicians, vehicle history and warranty claims.',
        icon: Wrench,
        color: 'bg-amber-600',
        status: 'Planned',
        subModules: [
            { title: 'Job Cards', description: 'The full repair lifecycle from intake to closed job.', icon: Wrench },
            { title: 'Labour Management', description: 'Labour codes, flat rates and time tracking.', icon: Timer },
            { title: 'Technician Management', description: 'Profiles, skills, efficiency and the job board.', icon: HardHat },
            { title: 'Parts Requisition', description: 'Parts issued from stock to jobs.', icon: PackageSearch },
            { title: 'Vehicle Registry', description: 'Customer vehicles with full service history.', icon: CarFront },
            { title: 'Job Costing', description: 'Labour + parts cost versus billed value per job.', icon: Gauge },
            { title: 'Warranty Claims', description: 'Warranty work and supplier claim-back.', icon: ShieldCheck },
            { title: 'Workshop Invoicing', description: 'Convert completed jobs to tax invoices.', icon: Receipt },
        ],
    },
    {
        key: 'customers',
        title: 'Customers',
        description: 'Customer profiles, trade accounts, credit, vehicles and loyalty.',
        icon: Users,
        color: 'bg-indigo-600',
        status: 'Planned',
        subModules: [
            { title: 'Customer Profiles', description: 'Individual, business, fleet and dealer customers.', icon: Users },
            { title: 'Trade Accounts', description: 'Credit accounts for garages, mechanics and fleets.', icon: Landmark },
            { title: 'Credit Management', description: 'Limits, ageing and account holds.', icon: Gauge },
            { title: 'Customer Vehicles', description: 'Registered vehicles per customer.', icon: CarFront },
            { title: 'Statements', description: 'Monthly account statements, emailed automatically.', icon: FileStack },
            { title: 'Loyalty Programme', description: 'Points and tier-based rewards.', icon: Award },
            { title: 'Customer Groups', description: 'Segment customers for pricing and marketing.', icon: UsersRound },
            { title: 'Communication Log', description: 'Calls, emails and notes per customer.', icon: MessageSquare },
        ],
    },
    {
        key: 'suppliers',
        title: 'Suppliers',
        description: 'Supplier profiles, price lists, approved suppliers and performance.',
        icon: Truck,
        color: 'bg-cyan-700',
        status: 'Planned',
        subModules: [
            { title: 'Supplier Profiles', description: 'Local and import supplier master records.', icon: Truck },
            { title: 'Supplier Price Lists', description: 'Import cost prices from supplier catalogues.', icon: ListOrdered },
            { title: 'Approved Supplier List', description: 'Preferred and alternate suppliers per part.', icon: BadgeCheck },
            { title: 'Supplier Performance', description: 'Delivery, fill rate and quality KPIs.', icon: TrendingUp },
            { title: 'Supplier Contacts', description: 'Multiple contacts per supplier.', icon: UsersRound },
        ],
    },
    {
        key: 'finance',
        title: 'Finance & Accounts',
        description: 'General ledger, receivables, payables, banking and VAT.',
        icon: Banknote,
        color: 'bg-emerald-700',
        status: 'Planned',
        subModules: [
            { title: 'Chart of Accounts', description: 'The full account structure for a spares business.', icon: ListTree },
            { title: 'General Ledger', description: 'Journals, GL enquiry and period control.', icon: BookOpen },
            { title: 'Accounts Receivable', description: 'Customer receipts, allocations and ageing.', icon: HandCoins },
            { title: 'Accounts Payable', description: 'Supplier payments and payment runs.', icon: Rows3 },
            { title: 'Cash & Bank Management', description: 'Bank accounts, statements and reconciliation.', icon: Landmark },
            { title: 'VAT Management', description: 'VAT returns, input and output tax.', icon: Percent },
            { title: 'Financial Reporting', description: 'Trial balance, income statement, balance sheet.', icon: Columns2 },
            { title: 'Period Management', description: 'Open, close and lock financial periods.', icon: Lock },
        ],
    },
    {
        key: 'vehicle-reference',
        title: 'Vehicle Reference',
        description: 'Makes, models, engine codes, fitment and cross-references.',
        icon: Car,
        color: 'bg-slate-600',
        status: 'Planned',
        subModules: [
            { title: 'Vehicle Makes', description: 'All car brands, prioritised for the regional market.', icon: Factory },
            { title: 'Models & Variants', description: 'Models, years, engines and trim variants.', icon: Car },
            { title: 'Parts Cross-Reference', description: 'OEM to aftermarket number mapping.', icon: Shuffle },
            { title: 'Fitment Guide', description: 'Find every part that fits a vehicle.', icon: Search },
            { title: 'Engine Codes', description: 'Engine code reference (1GD-FTV, 4JJ1, …).', icon: Cog },
            { title: 'Supersession Management', description: 'Track replaced part numbers with auto-redirect.', icon: GitBranch },
            { title: 'Technical Bulletins', description: 'Fitment warnings and service notes.', icon: AlertTriangle },
        ],
    },
    {
        key: 'reports',
        title: 'Reports & Analytics',
        description: 'Sales, stock, financial and workshop reporting with KPI dashboards.',
        icon: BarChart3,
        color: 'bg-purple-600',
        status: 'Planned',
        subModules: [
            { title: 'Executive Dashboard', description: 'Real-time KPIs for owners and managers.', icon: LayoutDashboard },
            { title: 'Sales Reports', description: 'Sales by period, part, customer, salesperson.', icon: ShoppingCart },
            { title: 'Inventory Reports', description: 'Stock on hand, ageing, dead stock, ABC analysis.', icon: Package },
            { title: 'Financial Reports', description: 'P&L, balance sheet, AR/AP ageing.', icon: Banknote },
            { title: 'Customer Reports', description: 'Top customers, dormant customers, loyalty.', icon: Users },
            { title: 'Supplier Reports', description: 'Spend, performance and delivery analysis.', icon: Truck },
            { title: 'Workshop Reports', description: 'Productivity, efficiency and job profitability.', icon: Wrench },
            { title: 'Scheduled Reports', description: 'Automated report generation and email delivery.', icon: Clock },
        ],
    },
    {
        key: 'system-admin',
        title: 'System Administration',
        description: 'Users, roles, company setup, branches and system configuration.',
        icon: Settings,
        color: 'bg-gray-700',
        status: 'Active',
        subModules: [
            { title: 'Users & Roles', description: 'User accounts and role-based access control.', icon: UserCog, route: 'auth.users.index', active: true },
            { title: 'Company Setup', description: 'Company details, logo and statutory information.', icon: Building2, route: 'admin.company.index', active: true },
            { title: 'Branch Management', description: 'Multi-branch configuration.', icon: MapPin, route: 'admin.branches.index', active: true },
            { title: 'Departments & Sections', description: 'Organisational structure.', icon: UsersRound, route: 'admin.departments.index', active: true },
            { title: 'Configuration Centre', description: 'Every business setting in one place, with per-branch overrides.', icon: SlidersHorizontal, route: 'admin.settings.index', active: true },
            { title: 'Activity Logs', description: 'Full audit trail of system actions.', icon: ScrollText, route: 'system.logs', active: true },
            { title: 'Currencies & Rates', description: 'USD, ZWG, ZAR and daily exchange rates.', icon: Coins, route: 'admin.currencies.index', active: true },
            { title: 'Number Sequences', description: 'Document numbering formats per type.', icon: Hash, route: 'admin.sequences.index', active: true },
            { title: 'Print Templates', description: 'Invoice, receipt and document layouts.', icon: Printer },
            { title: 'Email & SMS', description: 'Delivery settings and message templates.', icon: Mail },
            { title: 'Notifications Centre', description: 'Alert routing — bell, email and SMS.', icon: Bell },
            { title: 'System Health', description: 'Integrity dashboard — books balanced, stock true.', icon: HeartPulse },
            { title: 'Backup Management', description: 'Database backup scheduling and restore.', icon: DatabaseBackup },
            { title: 'Password Policy', description: 'Password rules and expiry.', icon: KeyRound },
        ],
    },
];

export function getModule(key) {
    return MODULES.find((m) => m.key === key);
}
