import {
    Package, ShoppingCart, Factory, Wrench, Users, Truck, Banknote, Car,
    BarChart3, Settings, PackageSearch, FolderTree, Tags, Layers,
    SlidersHorizontal, ArrowLeftRight, MapPin, ClipboardCheck, RefreshCw,
    ScanBarcode, FileText, ClipboardList, Receipt, Undo2, ListOrdered,
    Percent, CalendarClock, PauseCircle, FileInput, ListPlus, PackageCheck,
    FileSpreadsheet, FileMinus, PackageX, Ship, Scale, KanbanSquare,
    HardHat, Timer, CarFront, ShieldCheck, Gauge, FileStack, Award,
    MessageSquare, UsersRound, BadgeCheck, TrendingUp, BookOpen, PenLine,
    ListTree, HandCoins, Hourglass, Rows3, Landmark, GitCompare, Calendar,
    Lock, Columns2, Search, Shuffle, Cog, GitBranch, AlertTriangle, Upload,
    LayoutDashboard, Clock, Building2, UserCog, KeyRound, ScrollText,
    DatabaseBackup, Coins, Hash, Printer, Mail, Bell, HeartPulse,
} from 'lucide-react';

export const MODULES = [
    {
        key: 'inventory',
        title: 'Inventory Management',
        description: 'Parts catalogue, stock control, bin locations, stock takes and reorder management.',
        icon: Package,
        color: 'bg-orange-600',
        status: 'Active',
        subModules: [
            { title: 'Parts Catalogue', description: 'Master data for every part — SKUs, OEM numbers, barcodes, images.', icon: PackageSearch, route: 'inventory.parts.index', active: true },
            { title: 'Stock Control', description: 'Real-time stock levels per branch, adjustments and movement ledger.', icon: Layers, route: 'inventory.stock.index', active: true },
            { title: 'Bin Locations', description: 'Physical warehouse shelf and bin mapping.', icon: MapPin, route: 'inventory.bins.index', active: true },
            { title: 'Stock Takes', description: 'Full counts, cycle counts and variance resolution.', icon: ClipboardCheck, route: 'inventory.stock-takes.index', active: true },
            { title: 'Reorder Management', description: 'Min/max levels, reorder points and auto purchase requests.', icon: RefreshCw, route: 'inventory.reorder.index', active: true },
            { title: 'Parts Fitment Guide', description: 'Which parts fit which vehicles — make, model, year, engine.', icon: Car, route: 'vehicle-ref.fitment', active: true },
            { title: 'Serial & Batch Tracking', description: 'Individual tracking for engines, gearboxes and batches.', icon: ScanBarcode, route: 'inventory.serials.index', active: true },
            { title: 'Category Management', description: 'Hierarchical parts categorisation tree.', icon: FolderTree, route: 'inventory.categories.index', active: true },
        ],
    },
    {
        key: 'sales',
        title: 'Sales & POS',
        description: 'Counter sales, quotations, invoicing, price lists and promotions.',
        icon: ShoppingCart,
        color: 'bg-blue-600',
        status: 'Active',
        subModules: [
            { title: 'Counter Sales (POS)', description: 'Fast walk-in sales with barcode scanning and split payments.', icon: ShoppingCart, route: 'sales.pos', active: true },
            { title: 'Quotations', description: 'Formal quotes with expiry and one-click conversion.', icon: FileText, route: 'sales.quotes.index', active: true },
            { title: 'Sales Orders', description: 'Back-orders, stock reservations and delivery scheduling.', icon: ClipboardList, route: 'sales.orders.index', active: true },
            { title: 'Tax Invoices', description: 'Gapless invoicing with VAT and GL posting.', icon: Receipt, route: 'sales.invoices.index', active: true },
            { title: 'Credit Notes & Returns', description: 'Customer returns, refunds and exchanges.', icon: Undo2, route: 'sales.credit-notes.index', active: true },
            { title: 'Price Lists', description: 'Retail, trade, wholesale and VIP pricing tiers.', icon: ListOrdered, route: 'sales.price-lists.index', active: true },
            { title: 'Promotions & Discounts', description: 'Time-based deals, bulk discounts and bundles.', icon: Percent, route: 'sales.promotions.index', active: true },
            { title: 'Lay-by Management', description: 'Deposit-based payment plans.', icon: CalendarClock, route: 'sales.laybys.index', active: true },
            { title: 'Delivery Notes', description: 'Delivery documentation for shipped orders.', icon: Truck, route: 'sales.delivery-notes.index', active: true },
        ],
    },
    {
        key: 'purchasing',
        title: 'Purchasing',
        description: 'Purchase orders, goods receiving, supplier invoices and imports.',
        icon: Factory,
        color: 'bg-teal-600',
        status: 'Active',
        subModules: [
            { title: 'Purchase Requisitions', description: 'Internal requests to buy parts, auto-raised from reorder alerts.', icon: ListPlus, route: 'inventory.reorder.index', active: true },
            { title: 'Purchase Orders', description: 'Formal orders to suppliers with approvals and currency support.', icon: FileInput, route: 'purchasing.orders.index', active: true },
            { title: 'Goods Received Notes', description: 'Receiving, quality checks, putaway and landed costs.', icon: PackageCheck, route: 'purchasing.grns.index', active: true },
            { title: 'Supplier Invoices', description: '3-way matching against PO and GRN.', icon: FileSpreadsheet, route: 'purchasing.invoices.index', active: true },
            { title: 'Supplier Credit Notes', description: 'Credits for returns, corrections and rebates.', icon: FileMinus, route: 'purchasing.supplier-credits.index', active: true },
            { title: 'Returns to Supplier', description: 'RMA-tracked returns of damaged or incorrect goods.', icon: PackageX, route: 'purchasing.returns.index', active: true },
            { title: 'Import Management', description: 'International shipments, customs and clearing.', icon: Ship, route: 'purchasing.imports.index', active: true },
            { title: 'Price Comparison', description: 'Compare supplier costs for the same part.', icon: Scale, route: 'purchasing.price-comparison.index', active: true },
        ],
    },
    {
        key: 'workshop',
        title: 'Workshop',
        description: 'Job cards, labour, technicians, vehicle history and warranty claims.',
        icon: Wrench,
        color: 'bg-amber-600',
        status: 'Active',
        subModules: [
            { title: 'Job Cards', description: 'The full repair lifecycle from intake to closed job.', icon: Wrench, route: 'workshop.jobs.index', active: true },
            { title: 'Technician Board', description: 'Live jobs grouped by stage.', icon: KanbanSquare, route: 'workshop.board', active: true },
            { title: 'Labour Management', description: 'Labour codes, flat rates and make-specific overrides.', icon: Timer, route: 'workshop.labour.index', active: true },
            { title: 'Technician Management', description: 'Profiles, skills, cost rates and workload.', icon: HardHat, route: 'workshop.technicians.index', active: true },
            { title: 'Vehicle Registry', description: 'Customer vehicles with full service history.', icon: CarFront, route: 'workshop.vehicles.index', active: true },
            { title: 'Parts Requisition', description: 'Parts issued from stock to jobs.', icon: PackageSearch, route: 'workshop.jobs.index', active: true },
            { title: 'Job Costing', description: 'Labour + parts cost versus billed value per job.', icon: Gauge, route: 'reports.workshop.index', active: true },
            { title: 'Warranty Claims', description: 'Warranty work and supplier claim-back.', icon: ShieldCheck, route: 'workshop.warranty.index', active: true },
            { title: 'Workshop Invoicing', description: 'Convert completed jobs to tax invoices.', icon: Receipt, route: 'workshop.jobs.index', active: true },
        ],
    },
    {
        key: 'customers',
        title: 'Customers',
        description: 'Customer profiles, trade accounts, credit, vehicles and loyalty.',
        icon: Users,
        color: 'bg-indigo-600',
        status: 'Active',
        subModules: [
            { title: 'Customer Profiles', description: 'Individual, business, fleet and dealer customers.', icon: Users, route: 'customers.index', active: true },
            { title: 'Trade Accounts', description: 'Credit accounts for garages, mechanics and fleets.', icon: Landmark, route: 'customers.index', active: true },
            { title: 'Credit Management', description: 'Limits, ageing and account holds.', icon: Gauge, route: 'reports.customers.index', active: true },
            { title: 'Customer Vehicles', description: 'Registered vehicles per customer.', icon: CarFront, route: 'workshop.vehicles.index', active: true },
            { title: 'Statements', description: 'Account statements printed from any customer.', icon: FileStack, route: 'customers.index', active: true },
            { title: 'Loyalty Programme', description: 'Points and tier-based rewards.', icon: Award, route: 'customers.loyalty.index', active: true },
            { title: 'Customer Groups', description: 'Segment customers for pricing and marketing.', icon: UsersRound, route: 'customers.groups.index', active: true },
            { title: 'Communication Log', description: 'Calls, emails and notes per customer.', icon: MessageSquare, route: 'customers.comms.index', active: true },
        ],
    },
    {
        key: 'suppliers',
        title: 'Suppliers',
        description: 'Supplier profiles, price lists, approved suppliers and performance.',
        icon: Truck,
        color: 'bg-cyan-700',
        status: 'Active',
        subModules: [
            { title: 'Supplier Profiles', description: 'Local and import supplier master records.', icon: Truck, route: 'suppliers.index', active: true },
            { title: 'Supplier Price Lists', description: 'Import cost prices from supplier catalogues.', icon: ListOrdered, route: 'suppliers.index', active: true },
            { title: 'Approved Supplier List', description: 'Preferred and alternate suppliers per part.', icon: BadgeCheck, route: 'suppliers.approved.index', active: true },
            { title: 'Supplier Performance', description: 'Delivery, fill rate and quality KPIs.', icon: TrendingUp, route: 'suppliers.performance.index', active: true },
            { title: 'Supplier Contacts', description: 'Multiple contacts per supplier.', icon: UsersRound, route: 'suppliers.contacts.index', active: true },
        ],
    },
    {
        key: 'finance',
        title: 'Finance & Accounts',
        description: 'General ledger, receivables, payables, banking and VAT.',
        icon: Banknote,
        color: 'bg-emerald-700',
        status: 'Active',
        subModules: [
            { title: 'Chart of Accounts', description: 'The full account structure for a spares business.', icon: ListTree, route: 'finance.coa.index', active: true },
            { title: 'General Ledger', description: 'Journals, GL enquiry and period control.', icon: BookOpen, route: 'finance.gl.index', active: true },
            { title: 'Accounts Receivable', description: 'Customer receipts, allocations and ageing.', icon: HandCoins, route: 'finance.receipts.index', active: true },
            { title: 'Accounts Payable', description: 'Supplier payments and payment runs.', icon: Rows3, route: 'finance.payments.index', active: true },
            { title: 'Cash & Bank Management', description: 'Bank accounts, statements and reconciliation.', icon: Landmark, route: 'finance.bank.index', active: true },
            { title: 'VAT Management', description: 'VAT returns, input and output tax.', icon: Percent, route: 'finance.vat.index', active: true },
            { title: 'Financial Reporting', description: 'Trial balance, income statement, balance sheet.', icon: Columns2, route: 'finance.reports.trial-balance', active: true },
            { title: 'Period Management', description: 'Open, close and lock financial periods.', icon: Lock, route: 'finance.periods.index', active: true },
        ],
    },
    {
        key: 'vehicle-reference',
        title: 'Vehicle Reference',
        description: 'Makes, models, engine codes, fitment and cross-references.',
        icon: Car,
        color: 'bg-slate-600',
        status: 'Active',
        subModules: [
            { title: 'Vehicle Makes', description: 'All car brands, prioritised for the regional market.', icon: Factory, route: 'vehicle-ref.makes.index', active: true },
            { title: 'Models & Variants', description: 'Models, years, engines and trim variants.', icon: Car, route: 'vehicle-ref.models.index', active: true },
            { title: 'Parts Cross-Reference', description: 'OEM to aftermarket number mapping.', icon: Shuffle, route: 'vehicle-ref.cross-ref', active: true },
            { title: 'Fitment Guide', description: 'Find every part that fits a vehicle.', icon: Search, route: 'vehicle-ref.fitment', active: true },
            { title: 'Engine Codes', description: 'Engine code reference (1GD-FTV, 4JJ1, …).', icon: Cog, route: 'vehicle-ref.engines.index', active: true },
            { title: 'Supersession Management', description: 'Track replaced part numbers with auto-redirect.', icon: GitBranch, route: 'vehicle-ref.supersessions.index', active: true },
            { title: 'Technical Bulletins', description: 'Fitment warnings and service notes.', icon: AlertTriangle, route: 'vehicle-ref.bulletins.index', active: true },
        ],
    },
    {
        key: 'reports',
        title: 'Reports & Analytics',
        description: 'Sales, stock, financial and workshop reporting with KPI dashboards.',
        icon: BarChart3,
        color: 'bg-purple-600',
        status: 'Active',
        subModules: [
            { title: 'Executive Dashboard', description: 'Real-time KPIs for owners and managers.', icon: LayoutDashboard, route: 'reports.dashboard', active: true },
            { title: 'Sales Reports', description: 'Summary, by category, top parts and customers.', icon: ShoppingCart, route: 'reports.sales.index', active: true },
            { title: 'Inventory Reports', description: 'Stock on hand, value (GL-reconciled) and ageing.', icon: Package, route: 'reports.inventory.index', active: true },
            { title: 'Financial Reports', description: 'Trial balance, P&L, balance sheet.', icon: Banknote, route: 'finance.reports.trial-balance', active: true },
            { title: 'Customer Reports', description: 'Ageing, top customers, dormant, credit review.', icon: Users, route: 'reports.customers.index', active: true },
            { title: 'Supplier Reports', description: 'Spend, aged creditors and open POs.', icon: Truck, route: 'reports.suppliers.index', active: true },
            { title: 'Workshop Reports', description: 'Productivity and job profitability.', icon: Wrench, route: 'reports.workshop.index', active: true },
            { title: 'Scheduled Reports', description: 'Automated report generation and email delivery.', icon: Clock, route: 'reports.scheduled.index', active: true },
        ],
    },
    {
        key: 'system-admin',
        title: 'System Administration',
        description: 'Users, roles, company setup, branches and system configuration.',
        icon: Settings,
        color: 'bg-gray-700',
        status: 'Active',
        subModules: [
            { title: 'Users & Roles', description: 'User accounts and role-based access control.', icon: UserCog, route: 'auth.users.index', active: true },
            { title: 'Company Setup', description: 'Company details, logo and statutory information.', icon: Building2, route: 'admin.company.index', active: true },
            { title: 'Branch Management', description: 'Multi-branch configuration.', icon: MapPin, route: 'admin.branches.index', active: true },
            { title: 'Departments & Sections', description: 'Organisational structure.', icon: UsersRound, route: 'admin.departments.index', active: true },
            { title: 'Configuration Centre', description: 'Every business setting in one place, with per-branch overrides.', icon: SlidersHorizontal, route: 'admin.settings.index', active: true },
            { title: 'Activity Logs', description: 'Full audit trail of system actions.', icon: ScrollText, route: 'system.logs', active: true },
            { title: 'Currencies & Rates', description: 'USD, ZWG, ZAR and daily exchange rates.', icon: Coins, route: 'admin.currencies.index', active: true },
            { title: 'Number Sequences', description: 'Document numbering formats per type.', icon: Hash, route: 'admin.sequences.index', active: true },
            { title: 'Print Templates', description: 'Invoice, receipt and document layouts.', icon: Printer, route: 'admin.print-templates.index', active: true },
            { title: 'Email & SMS', description: 'Delivery settings and message templates.', icon: Mail, route: 'admin.comms.index', active: true },
            { title: 'Notifications Centre', description: 'Alert routing — bell, email and SMS.', icon: Bell, route: 'admin.notifications-centre.index', active: true },
            { title: 'System Health', description: 'Integrity dashboard — books balanced, stock true.', icon: HeartPulse, route: 'admin.health', active: true },
            { title: 'Backup Management', description: 'Database backup scheduling and restore.', icon: DatabaseBackup, route: 'admin.backups.index', active: true },
            { title: 'Password Policy', description: 'Password rules and expiry.', icon: KeyRound, route: 'admin.password-policy.index', active: true },
        ],
    },
];

export function getModule(key) {
    return MODULES.find((m) => m.key === key);
}
